import { rest } from 'msw'
import { url } from './beer-search'
import { UtBeerSearchResponse } from './beer-search.types'

export default rest.get(url, (_, res, ctx) => {
  return res(ctx.delay(100), ctx.status(200), ctx.json(getMockedData()))
})

function getMockedData(): UtBeerSearchResponse {
  return {
    meta: {
      code: 200,
      response_time: { time: 0.31, measure: 'seconds' },
      init_time: { time: 0, measure: 'seconds' },
    },
    notifications: {
      type: 'notifications',
      unread_count: {
        comments: 0,
        toasts: 0,
        friends: 0,
        messages: 0,
        venues: 0,
        veunes: 0,
        others: 0,
        news: 0,
      },
    },
    response: {
      message: '',
      time_taken: 0.036,
      brewery_id: 0,
      search_type: '',
      type_id: 0,
      search_version: 4,
      found: 22423,
      offset: 0,
      limit: 25,
      term: 'Pilsner',
      parsed_term: 'Pilsner',
      beers: {
        count: 25,
        items: [
          {
            checkin_count: 1461969,
            have_had: false,
            your_count: 0,
            beer: {
              bid: 5860,
              beer_name: 'Heineken',
              beer_label:
                'https://untappd.akamaized.net/site/beer_logos/beer-5860_a68ef_sm.jpeg',
              beer_abv: 5,
              beer_slug: 'heineken-heineken',
              beer_ibu: 19,
              beer_description:
                'Heineken is a 5% ABV euro pale lager, made by Heineken International since 1873. It is available in a 4.3% alcohol by volume, in countries such as Ireland. It is the flagship product of the company and is made of purified water, malted barley, hops, and yeast. In 1886 H. Elion finished the development of the Heineken A-yeast. This is the yeast that is still used for the beer. The beer is force carbonated. It is popular in the United States, Europe and Middle Eastern countries.',
              created_at: 'Fri, 17 Sep 2010 12:09:12 +0000',
              beer_style: 'Lager - Euro Pale',
              in_production: 1,
              auth_rating: 0,
              wish_list: false,
            },
            brewery: {
              brewery_id: 1400,
              brewery_name: 'Heineken',
              brewery_slug: 'heineken',
              brewery_page_url: '/Heineken',
              brewery_type: 'Macro Brewery',
              brewery_label:
                'https://untappd.akamaized.net/site/brewery_logos/brewery-1400_b323a.jpeg',
              country_name: 'Netherlands',
              contact: {
                twitter: 'heineken',
                facebook: 'https://www.facebook.com/heineken',
                instagram: '',
                url: 'http://www.heineken.com',
              },
              location: {
                brewery_city: 'Zoeterwoude',
                brewery_state: 'Zuid-Holland',
                lat: 52.1375,
                lng: 4.53398,
              },
              brewery_active: 1,
            },
          },
          {
            checkin_count: 536089,
            have_had: false,
            your_count: 0,
            beer: {
              bid: 37936,
              beer_name: 'Pilsner Urquell',
              beer_label:
                'https://untappd.akamaized.net/site/beer_logos/beer-37936_fb045_sm.jpeg',
              beer_abv: 4.4,
              beer_slug: 'plzensky-prazdroj-pilsner-urquell',
              beer_ibu: 40,
              beer_description:
                'In 1842, at our brewery in Plzeň, brewer Josef Groll introduced the world to the first golden ‘pilsner’ lager, and changed beer forever. His invention soon became the most popular style of beer on the planet.\r\n\r\nWe’ve brewed Pilsner Urquell in the same brewery using the same recipe for over 175 years. Today, we still insist on using traditional methods, like triple decoction and parallel brewing in wooden lagering barrels. It takes longer but means we never compromise on our taste.\r\n\r\nPilsner Urquell’s signature flavour balances sweetness from the triple-decocted malt, and bitterness from our Saaz hops. The thick head of dense wet foam adds smoothness and seals in flavour and aroma.\r\n\r\nIn every sip of Pilsner Urquell you’ll notice a refreshing crispness from natural carbonation, then subtle caramel tones and a clean finish with a pleasing hoppy bitterness.',
              created_at: 'Fri, 18 Mar 2011 00:23:31 +0000',
              beer_style: 'Pilsner - Czech',
              in_production: 1,
              auth_rating: 0,
              wish_list: false,
            },
            brewery: {
              brewery_id: 1459,
              brewery_name: 'Plzeňský Prazdroj',
              brewery_slug: 'plzensky-prazdroj',
              brewery_page_url: '/plzenskyprazdroj',
              brewery_type: 'Macro Brewery',
              brewery_label:
                'https://untappd.akamaized.net/site/brewery_logos/brewery-1459_c1a81.jpeg',
              country_name: 'Czech Republic',
              contact: {
                twitter: 'prazdroj1',
                facebook: 'https://www.facebook.com/PilsnerUrquellGlobal/',
                instagram: 'pilsnerurquell',
                url: 'http://www.prazdroj.cz',
              },
              location: {
                brewery_city: 'Pilsen',
                brewery_state: 'Jihozápad',
                lat: 49.7474,
                lng: 13.3879,
              },
              brewery_active: 1,
            },
          },
          {
            checkin_count: 456014,
            have_had: false,
            your_count: 0,
            beer: {
              bid: 7221,
              beer_name: 'Grolsch Premium Lager',
              beer_label:
                'https://untappd.akamaized.net/site/beer_logos/beer-7221_a0e35_sm.jpeg',
              beer_abv: 5,
              beer_slug: 'koninklijke-grolsch-grolsch-premium-lager',
              beer_ibu: 28,
              beer_description:
                "A traditional Pilsner style beer with a big hoppy flavour and bite owing to dry hopping late in the brewing process. The zesty and fragrant hops make for a refreshingly dry finish and a slight sweet and sharp zing to the palate, which are best enjoyed with rich, creamy foods like pork sausage and mustard mash, quality fish and chips or cheese like Old Amsterdam, Edam or Brie. Grolsch is known to use a distinctively shaped bottle for its beer, known as de beugel or 'swingtop'.",
              created_at: 'Thu, 04 Nov 2010 10:16:04 +0000',
              beer_style: 'Pilsner - Other',
              in_production: 1,
              auth_rating: 0,
              wish_list: false,
            },
            brewery: {
              brewery_id: 4058,
              brewery_name: 'Koninklijke Grolsch',
              brewery_slug: 'koninklijke-grolsch',
              brewery_page_url: '/KoninklijkeGrolsch',
              brewery_type: 'Macro Brewery',
              brewery_label:
                'https://untappd.akamaized.net/site/brewery_logos/brewery-GrolschBierbrouwerijNV_4058.jpeg',
              country_name: 'Netherlands',
              contact: {
                twitter: 'Grolsch',
                facebook: 'https://www.facebook.com/grolsch',
                instagram: '',
                url: 'http://www.grolsch.nl',
              },
              location: {
                brewery_city: 'Enschede',
                brewery_state: 'Overijssel',
                lat: 52.207,
                lng: 6.81712,
              },
              brewery_active: 1,
            },
          },
          {
            checkin_count: 405087,
            have_had: false,
            your_count: 0,
            beer: {
              bid: 5850,
              beer_name: 'Pacífico Clara',
              beer_label:
                'https://untappd.akamaized.net/site/beer_logos/beer-5850_8ac62_sm.jpeg',
              beer_abv: 4.5,
              beer_slug: 'grupo-modelo-pacifico-clara',
              beer_ibu: 15,
              beer_description:
                'Pacifico Clara Mexican Beer is adventurous with a hearty, crisp taste of citrus and ocean mist. Enjoy this lightly bitter import beer with grilled shrimp or a Baja taco.',
              created_at: 'Sat, 21 Aug 2010 13:29:32 +0000',
              beer_style: 'Lager - American',
              in_production: 1,
              auth_rating: 0,
              wish_list: false,
            },
            brewery: {
              brewery_id: 618,
              brewery_name: 'Grupo Modelo',
              brewery_slug: 'grupo-modelo',
              brewery_page_url: '/GrupoModelo',
              brewery_type: 'Macro Brewery',
              brewery_label:
                'https://untappd.akamaized.net/site/brewery_logos/brewery-GrupoModeloSAdeCV_618.jpeg',
              country_name: 'Mexico',
              contact: {
                twitter: 'GrupoModelo_MX',
                facebook: 'https://www.facebook.com/Grupo-Modelo-140990106243621/',
                instagram: '',
                url: 'http://www.gmodelo.mx',
              },
              location: {
                brewery_city: 'Nava',
                brewery_state: 'Coahuila de Zaragoza',
                lat: 28.5769,
                lng: -100.597,
              },
              brewery_active: 1,
            },
          },
          {
            checkin_count: 348751,
            have_had: false,
            your_count: 0,
            beer: {
              bid: 10703,
              beer_name: 'Warsteiner Premium Verum / German Pilsener',
              beer_label:
                'https://untappd.akamaized.net/site/beer_logos/beer-10703_646a2_sm.jpeg',
              beer_abv: 4.8,
              beer_slug: 'warsteiner-warsteiner-premium-verum-german-pilsener',
              beer_ibu: 28,
              beer_description:
                'Enjoy this world-class international premium pilsener.\r\n\r\nUnique: the slightly tart taste experience.\r\n\r\nExceptional: the top quality of the ingredients.\r\n\r\nInimitable: the exquisite premium character.\r\n\r\nPleasantly light: thanks to especially soft brewing water.\r\n\r\n“Öko-Test”: “First Class”\r\n\r\nThe “Öko Test” magazine compared 46 beers including known brands distributed throughout Germany and regional brands. The Warsteiner Brewery’s Premium-Pils was rated “First Class” by the Öko-Test jurors as the best beer distributed throughout Germany from a family-run brewery (August 2009).\r\n\r\nThis outstanding result impressively underscores Warsteiner’s traditional quality attributes.',
              created_at: 'Wed, 24 Nov 2010 15:55:19 +0000',
              beer_style: 'Pilsner - German',
              in_production: 1,
              auth_rating: 0,
              wish_list: false,
            },
            brewery: {
              brewery_id: 1337,
              brewery_name: 'Warsteiner',
              brewery_slug: 'warsteiner',
              brewery_page_url: '/Warsteiner',
              brewery_type: 'Macro Brewery',
              brewery_label:
                'https://untappd.akamaized.net/site/brewery_logos/brewery-1337_24802.jpeg',
              country_name: 'Germany',
              contact: {
                twitter: 'warsteiner',
                facebook: 'http://www.facebook.com/Warsteiner',
                instagram: 'warsteiner',
                url: 'http://www.warsteiner.de',
              },
              location: {
                brewery_city: 'Warstein',
                brewery_state: 'Nordrhein-Westfalen',
                lat: 51.4215,
                lng: 8.34323,
              },
              brewery_active: 1,
            },
          },
          {
            checkin_count: 299137,
            have_had: false,
            your_count: 0,
            beer: {
              bid: 17252,
              beer_name: 'Bitburger Premium Pils',
              beer_label:
                'https://untappd.akamaized.net/site/beer_logos/beer-17252_fc89f_sm.jpeg',
              beer_abv: 4.8,
              beer_slug: 'bitburger-brauerei-bitburger-premium-pils',
              beer_ibu: 38,
              beer_description: 'Bitburger Premium Pils / Premium Beer',
              created_at: 'Sat, 25 Dec 2010 23:19:39 +0000',
              beer_style: 'Pilsner - German',
              in_production: 1,
              auth_rating: 0,
              wish_list: false,
            },
            brewery: {
              brewery_id: 131,
              brewery_name: 'Bitburger Brauerei',
              brewery_slug: 'bitburger-brauerei',
              brewery_page_url: '/Bitburger-Braugruppe',
              brewery_type: 'Regional Brewery',
              brewery_label:
                'https://untappd.akamaized.net/site/brewery_logos/brewery-131_4e980.jpeg',
              country_name: 'Germany',
              contact: {
                twitter: '',
                facebook: 'https://www.facebook.com/Bitburger/',
                instagram: 'https://www.instagram.com/bitburger/',
                url: 'http://www.bitburger.de',
              },
              location: {
                brewery_city: 'Bitburg',
                brewery_state: 'Rheinland-Pfalz',
                lat: 49.9746,
                lng: 6.52166,
              },
              brewery_active: 1,
            },
          },
          {
            checkin_count: 297427,
            have_had: false,
            your_count: 0,
            beer: {
              bid: 72160,
              beer_name: 'Amstel',
              beer_label:
                'https://untappd.akamaized.net/site/beer_logos/beer-72160_68a98_sm.jpeg',
              beer_abv: 5,
              beer_slug: 'amstel-bier-amstel',
              beer_ibu: 21,
              beer_description:
                'The distinctive, golden Amstel ® beer with its mildly bitter taste and excellent quality has become well known around the World.\r\n\r\n- Al sinds 1870 wordt Amstel Pilsener volmout gebrouwen met natuurlijke ingrediënten. Het resultaat is een helder goudgeel bier met een volle, toegankelijke smaak en een stevige schuimkraag. Het perfecte bier om te delen met vrienden.\r\n\r\n- Amstel 100% malta es el inicio de todo, nuestro máximo motivo de orgullo. Originaria de Ámsterdam, su receta hecha únicamente con ingredientes naturales se mantiene intacta desde 1870, conservando la tradición de los maestros cerveceros.',
              created_at: 'Mon, 15 Aug 2011 20:35:40 +0000',
              beer_style: 'Lager - Euro Pale',
              in_production: 1,
              auth_rating: 0,
              wish_list: false,
            },
            brewery: {
              brewery_id: 37,
              brewery_name: 'Amstel Bier',
              brewery_slug: 'amstel-bier',
              brewery_page_url: '/AmstelBier',
              brewery_type: 'Macro Brewery',
              brewery_label:
                'https://untappd.akamaized.net/site/brewery_logos/brewery-37_7a6da.jpeg',
              country_name: 'Netherlands',
              contact: {
                twitter: 'amstelbier_nl',
                facebook: 'https://www.facebook.com/Amstel',
                instagram: '',
                url: 'http://www.amstel.nl/',
              },
              location: {
                brewery_city: 'Zoeterwoude',
                brewery_state: 'Zuid-Holland',
                lat: 52.1375,
                lng: 4.53398,
              },
              brewery_active: 1,
            },
          },
          {
            checkin_count: 288537,
            have_had: false,
            your_count: 0,
            beer: {
              bid: 6870,
              beer_name: "Beck's",
              beer_label:
                'https://untappd.akamaized.net/site/beer_logos/beer-Becks_6870.jpeg',
              beer_abv: 4.9,
              beer_slug: 'brauerei-beck-becks',
              beer_ibu: 21,
              beer_description:
                'Our original Beck’s is a classic German lager beer with a distinctive full-bodied taste, fresh "hoppy" bouquet, golden color and full rich head. Adding to its complexity is a slightly fruity but firm crispness and a dry, clean finish.',
              created_at: 'Wed, 27 Oct 2010 11:35:33 +0000',
              beer_style: 'Pilsner - German',
              in_production: 1,
              auth_rating: 0,
              wish_list: false,
            },
            brewery: {
              brewery_id: 95,
              brewery_name: 'Brauerei Beck',
              brewery_slug: 'brauerei-beck',
              brewery_page_url: '/w/brauerei-beck/95',
              brewery_type: 'Macro Brewery',
              brewery_label:
                'https://untappd.akamaized.net/site/brewery_logos/brewery-BrauereiBeckCo_95.jpeg',
              country_name: 'Germany',
              contact: {
                twitter: '',
                facebook: 'https://www.facebook.com/becks.de/',
                instagram: '',
                url: 'http://www.becks.de',
              },
              location: {
                brewery_city: 'Neustadt',
                brewery_state: 'Bremen',
                lat: 53.0768,
                lng: 8.79237,
              },
              brewery_active: 1,
            },
          },
          {
            checkin_count: 244713,
            have_had: false,
            your_count: 0,
            beer: {
              bid: 5210,
              beer_name: "Mama's Little Yella Pils",
              beer_label:
                'https://untappd.akamaized.net/site/beer_logos/beer-5210_bb9f7_sm.jpeg',
              beer_abv: 4.7,
              beer_slug: 'oskar-blues-brewery-mamas-little-yella-pils',
              beer_ibu: 35,
              beer_description:
                "Mama's Little Yella Pils - Our upcoming new canned good is a small-batch version of the beer that made Pilsen, Czechoslovakia famous. Mama's is made with hearty amounts of pale malt, German specialty malts, and a blend of traditional (Saaz) and 21st century Bavarian hops. Our first canned lager, it's also fermented at cool temperatures with a German yeast.\r\n\r\nThis tasteful reality Czech is the perfect antidote for the watered-down versions of pilsner clogging Americaâ's shelves. And Mama's gentle hopping (about 35 IBUs) and low ABV (just 4.7%) mean we're finally honoring consumer requests for a delicious but less-challenging beer. (Hey, we like a good low-dose session beer, too.) Look for our Gold Metal Winner on US shelves in March.\r\n\r\nSadly, the Feds rejected our Take Two and Call Us in the Morning line on the can.",
              created_at: 'Sat, 21 Aug 2010 14:26:35 +0000',
              beer_style: 'Pilsner - Czech',
              in_production: 1,
              auth_rating: 0,
              wish_list: false,
            },
            brewery: {
              brewery_id: 956,
              brewery_name: 'Oskar Blues Brewery',
              brewery_slug: 'oskar-blues-brewery',
              brewery_page_url: '/oskarblues',
              brewery_type: 'Regional Brewery',
              brewery_label:
                'https://untappd.akamaized.net/site/brewery_logos/brewery-956_9066d.jpeg',
              country_name: 'United States',
              contact: {
                twitter: 'oskarblues',
                facebook: 'https://www.facebook.com/OskarBluesCANS/',
                instagram: 'oskarblues',
                url: 'http://www.oskarblues.com/',
              },
              location: {
                brewery_city: 'Longmont',
                brewery_state: 'CO',
                lat: 40.1391,
                lng: -105.122,
              },
              brewery_active: 1,
            },
          },
          {
            checkin_count: 233952,
            have_had: false,
            your_count: 0,
            beer: {
              bid: 5385,
              beer_name: 'Budweiser Budvar B:ORIGINAL / Czechvar B:ORIGINAL',
              beer_label:
                'https://untappd.akamaized.net/site/beer_logos/beer-5385_b720e_sm.jpeg',
              beer_abv: 5,
              beer_slug:
                'budejovicky-budvar-budweiser-budvar-boriginal-czechvar-boriginal',
              beer_ibu: 32,
              beer_description:
                'Czechvar in North America.\r\n\r\nOur premium pale lager is beer for real connoisseurs. The first-class female cones of top-quality Saaz hops, pure clean natural water from 300-metre deep artesian wells and carefully selected grains of a unique cultivar of Moravian barely make the premium lager a drink for real beer experts.\r\n\r\nA 750-year long tradition of brewing the original Beer from Budweis and a unique 90-day long maturing period amplify the beer’s exceptionality even more. Budweiser Budvar Premium Pale Lager can thus be savoured with all the senses. Firstly, your eye can see its beautiful golden colour and rich thick head, then you can smell its mild hop aroma and feel the misted glass in your palm, and finally use your taste buds to savour its mild medium-strong bitterness. Our premium pale lager will forever impress in your mind.\r\n\r\n',
              created_at: 'Sat, 21 Aug 2010 14:26:35 +0000',
              beer_style: 'Pilsner - Czech',
              in_production: 1,
              auth_rating: 0,
              wish_list: false,
            },
            brewery: {
              brewery_id: 245,
              brewery_name: 'Budějovický Budvar',
              brewery_slug: 'budejovicky-budvar',
              brewery_page_url: '/BudjovickBudvar',
              brewery_type: 'Regional Brewery',
              brewery_label:
                'https://untappd.akamaized.net/site/brewery_logos/brewery-245_00ee7.jpeg',
              country_name: 'Czech Republic',
              contact: {
                twitter: 'BudvarUK',
                facebook: 'https://www.facebook.com/BudejovickyBudvar/',
                instagram: '',
                url: 'http://www.budejovickybudvar.cz/',
              },
              location: {
                brewery_city: 'České Budějovice',
                brewery_state: 'Jihozápad',
                lat: 48.9936,
                lng: 14.4762,
              },
              brewery_active: 1,
            },
          },
          {
            checkin_count: 231682,
            have_had: false,
            your_count: 0,
            beer: {
              bid: 38700,
              beer_name: 'Staropramen Premium / Ležák',
              beer_label:
                'https://untappd.akamaized.net/site/beer_logos/beer-38700_653d5_sm.jpeg',
              beer_abv: 5,
              beer_slug: 'pivovary-staropramen-staropramen-premium-lezak',
              beer_ibu: 27,
              beer_description:
                'Barva, pěna, vůně a chuť vytváří unikátní senzorický profil tohoto spodně kvašeného ležáku uvařeného z 2 druhů sladů a 5 druhů chmele, včetně žateckého, který je srdcem tohoto piva. Znalec ocení typickou pivní vůni a chuť, které ve vzájemné harmonii dávají tomuto středně až silně prokvašenému ležáku příjemnou pitelnost, ležákovou plnost s osvěžujícím řízem.',
              created_at: 'Sun, 20 Mar 2011 09:21:04 +0000',
              beer_style: 'Pilsner - Czech',
              in_production: 1,
              auth_rating: 0,
              wish_list: false,
            },
            brewery: {
              brewery_id: 998,
              brewery_name: 'Pivovary Staropramen',
              brewery_slug: 'pivovary-staropramen',
              brewery_page_url: '/Pivovary-Staropramen',
              brewery_type: 'Macro Brewery',
              brewery_label:
                'https://untappd.akamaized.net/site/brewery_logos/brewery-998_314e6.jpeg',
              country_name: 'Czech Republic',
              contact: {
                twitter: 'staropramen',
                facebook: 'https://www.facebook.com/Staropramen',
                instagram: 'staropramen',
                url: 'http://www.staropramen.com/',
              },
              location: {
                brewery_city: 'Prague',
                brewery_state: 'Praha',
                lat: 50.0685,
                lng: 14.4066,
              },
              brewery_active: 1,
            },
          },
          {
            checkin_count: 196578,
            have_had: false,
            your_count: 0,
            beer: {
              bid: 9945,
              beer_name: 'Krombacher Pils',
              beer_label:
                'https://untappd.akamaized.net/site/beer_logos/beer-9945_3a43c_sm.jpeg',
              beer_abv: 4.8,
              beer_slug: 'krombacher-gruppe-krombacher-pils',
              beer_ibu: 24,
              beer_description:
                'Krombacher Pils - A pearl of nature.\r\n\r\nSituated in beautiful natural surroundings, the pure Felsquellwasser® (mountain spring water) provides the essence of purity that is captured in the unmistakable taste adventure that Krombacher Pils brings us. The taste of our beer is quite decisively characterised by the water it is brewed with.\r\nWith Krombacher Pils you enjoy a distinctive, finely bitter taste and a full-flavoured aroma – this is a genuine premium pilsner beer with an alcohol content of 4.8 %. Our modern production processes enhance the traditional recipe whilst complimenting the natural products that have been used for generations to create the unique brew that is Krombacher Pils.\r\n"Every 10th Pils consumed in Germany comes from Krombach. In Germany each second 60 glasses (0,2l) of Krombacher Pils are enjoyed."',
              created_at: 'Fri, 19 Nov 2010 11:51:46 +0000',
              beer_style: 'Pilsner - German',
              in_production: 1,
              auth_rating: 0,
              wish_list: false,
            },
            brewery: {
              brewery_id: 1569,
              brewery_name: 'Krombacher Gruppe',
              brewery_slug: 'krombacher-gruppe',
              brewery_page_url: '/w/krombacher-gruppe/1569',
              brewery_type: 'Macro Brewery',
              brewery_label:
                'https://untappd.akamaized.net/site/brewery_logos/brewery-KrombacherPrivatbrauereiKreuztal_1569.jpeg',
              country_name: 'Germany',
              contact: {
                twitter: 'krombacher',
                facebook: 'https://www.facebook.com/Krombacher/',
                instagram: 'krombacher',
                url: 'https://www.krombacher.de/',
              },
              location: {
                brewery_city: 'Kreuztal',
                brewery_state: 'Nordrhein-Westfalen',
                lat: 50.9909,
                lng: 7.95561,
              },
              brewery_active: 1,
            },
          },
          {
            checkin_count: 188754,
            have_had: false,
            your_count: 0,
            beer: {
              bid: 6797,
              beer_name: 'Tuborg Grøn',
              beer_label:
                'https://untappd.akamaized.net/site/beer_logos/beer-6797_09553_sm.jpeg',
              beer_abv: 4.6,
              beer_slug: 'carlsberg-group-tuborg-gron',
              beer_ibu: 18,
              beer_description:
                "Tuborg is a bottom-fermented lager beer, also brewed in Germany at 4.9% and at many other Carlsberg sites all over the world (ABV may vary). It's brewed from lager malt, a slightly roasted, bright type of malt which results in the well-known mild, fresh taste and aroma of flowers and grain. The beer is medium rich and lively with a moderate bitterness in the aftertaste.\r\n\r\nAlso brewed on license in India with 5% ABV.",
              created_at: 'Sat, 23 Oct 2010 17:38:54 +0000',
              beer_style: 'Pilsner - Other',
              in_production: 1,
              auth_rating: 0,
              wish_list: false,
            },
            brewery: {
              brewery_id: 344,
              brewery_name: 'Carlsberg Group',
              brewery_slug: 'carlsberg-group',
              brewery_page_url: '/CarlsbergGroup',
              brewery_type: 'Macro Brewery',
              brewery_label:
                'https://untappd.akamaized.net/site/brewery_logos/brewery-CarlsbergBrewery_344.jpeg',
              country_name: 'Denmark',
              contact: {
                twitter: 'carlsberggroup',
                facebook: 'http://www.facebook.com/Carlsberg',
                instagram: 'carlsberg',
                url: 'http://www.carlsberggroup.com',
              },
              location: {
                brewery_city: 'Copenhagen',
                brewery_state: 'Region Hovedstaden',
                lat: 55.6673,
                lng: 12.535,
              },
              brewery_active: 1,
            },
          },
          {
            checkin_count: 178391,
            have_had: false,
            your_count: 0,
            beer: {
              bid: 3820,
              beer_name: 'Prima Pils',
              beer_label:
                'https://untappd.akamaized.net/site/beer_logos/beer-3820_345da_sm.jpeg',
              beer_abv: 5.3,
              beer_slug: 'victory-brewing-company-prima-pils',
              beer_ibu: 43,
              beer_description:
                'Refreshingly bold and perfectly balanced, Prima has set the gold standard for Pilsners since 1996 with its German and Czech noble hops and German malt.',
              created_at: 'Sat, 21 Aug 2010 14:26:35 +0000',
              beer_style: 'Pilsner - German',
              in_production: 1,
              auth_rating: 0,
              wish_list: false,
            },
            brewery: {
              brewery_id: 1326,
              brewery_name: 'Victory Brewing Company',
              brewery_slug: 'victory-brewing-company',
              brewery_page_url: '/victorybeer',
              brewery_type: 'Regional Brewery',
              brewery_label:
                'https://untappd.akamaized.net/site/brewery_logos/brewery-1326_4578e.jpeg',
              country_name: 'United States',
              contact: {
                twitter: 'VictoryBeer',
                facebook: 'https://facebook.com/victorybeer',
                instagram: 'victorybeer',
                url: 'http://victorybeer.com/',
              },
              location: {
                brewery_city: 'Downingtown',
                brewery_state: 'PA',
                lat: 40.0061,
                lng: -75.6942,
              },
              brewery_active: 1,
            },
          },
          {
            checkin_count: 152902,
            have_had: false,
            your_count: 0,
            beer: {
              bid: 1589,
              beer_name: 'Radeberger Pilsner',
              beer_label:
                'https://untappd.akamaized.net/site/beer_logos/beer-1589_8b362_sm.jpeg',
              beer_abv: 4.8,
              beer_slug: 'radeberger-gruppe-radeberger-pilsner',
              beer_ibu: 33,
              beer_description:
                'Crowned the official drink by King Friedrich August III of Saxony, Radeberger, a pilsner style beer brewed near Dresden, is characterized by its dazzling and refreshing taste and has long been enjoyed by German nobility.',
              created_at: 'Sat, 21 Aug 2010 14:26:35 +0000',
              beer_style: 'Pilsner - German',
              in_production: 1,
              auth_rating: 0,
              wish_list: false,
            },
            brewery: {
              brewery_id: 4936,
              brewery_name: 'Radeberger Gruppe',
              brewery_slug: 'radeberger-gruppe',
              brewery_page_url: '/RadebergerGruppe',
              brewery_type: 'Macro Brewery',
              brewery_label:
                'https://untappd.akamaized.net/site/brewery_logos/brewery-4936_db567.jpeg',
              country_name: 'Germany',
              contact: {
                twitter: '',
                facebook: '',
                instagram: '',
                url: 'http://www.radeberger-gruppe.de',
              },
              location: {
                brewery_city: 'Frankfurt am Main',
                brewery_state: 'Hessen',
                lat: 50.0958,
                lng: 8.69188,
              },
              brewery_active: 1,
            },
          },
          {
            checkin_count: 152248,
            have_had: false,
            your_count: 0,
            beer: {
              bid: 74539,
              beer_name: 'Pivo Pils',
              beer_label:
                'https://untappd.akamaized.net/site/beer_logos/beer-74539_ed246_sm.jpeg',
              beer_abv: 5.3,
              beer_slug: 'firestone-walker-brewing-company-pivo-pils',
              beer_ibu: 40,
              beer_description:
                'Everything we love about classic German Pilsner with a hoppy Bohemian twist.  Pils is a bright straw colored lager beer with playful carbonation topped with beautiful white foam lace.  Delicate lightly toasted malt flavors underscore noble German hop character.  Hallertau-grown Magnum hops deliver the lupulin foundation while generous amounts of Spalter Select hops bring  floral aromatic and spicy herbal notes. As a twist on the traditional Pils, we dry hop with German Saphir for a touch of bergamot zest and lemongrass. A refreshing, light-bodied and hop-driven Pils.',
              created_at: 'Fri, 26 Aug 2011 19:28:44 +0000',
              beer_style: 'Pilsner - Other',
              in_production: 1,
              auth_rating: 0,
              wish_list: false,
            },
            brewery: {
              brewery_id: 524,
              brewery_name: 'Firestone Walker Brewing Company',
              brewery_slug: 'firestone-walker-brewing-company',
              brewery_page_url: '/firestonewalker',
              brewery_type: 'Regional Brewery',
              brewery_label:
                'https://untappd.akamaized.net/site/brewery_logos/brewery-524_e835d.jpeg',
              country_name: 'United States',
              contact: {
                twitter: 'FirestoneWalker',
                facebook: 'http://www.facebook.com/#!/firestone.walker',
                instagram: 'firestonewalker',
                url: 'http://www.firestonebeer.com/',
              },
              location: {
                brewery_city: 'Paso Robles',
                brewery_state: 'CA',
                lat: 35.5953,
                lng: -120.694,
              },
              brewery_active: 1,
            },
          },
          {
            checkin_count: 151658,
            have_had: false,
            your_count: 0,
            beer: {
              bid: 6725,
              beer_name: 'Pils',
              beer_label:
                'https://untappd.akamaized.net/site/beer_logos/beer-6725_ac727_sm.jpeg',
              beer_abv: 6,
              beer_slug: 'lagunitas-brewing-company-pils',
              beer_ibu: 35,
              beer_description:
                'Our only Unlimited Lager, brewed with loads of imported Saaz hops and a bottom-fermenting yeast strain that leaves it Light and Crisp and Easy to Slam, yet full of real flavor and all the things you yearn for.',
              created_at: 'Fri, 22 Oct 2010 09:26:00 +0000',
              beer_style: 'Pilsner - Czech',
              in_production: 1,
              auth_rating: 0,
              wish_list: false,
            },
            brewery: {
              brewery_id: 765,
              brewery_name: 'Lagunitas Brewing Company',
              brewery_slug: 'lagunitas-brewing-company',
              brewery_page_url: '/LagunitasBrewingCo',
              brewery_type: 'Macro Brewery',
              brewery_label:
                'https://untappd.akamaized.net/site/brewery_logos/brewery-765_b53eb.jpeg',
              country_name: 'United States',
              contact: {
                twitter: 'lagunitasbeer',
                facebook: 'https://www.facebook.com/LagunitasBrewingCo',
                instagram: 'lagunitasbeer',
                url: 'http://www.LAGUNITAS.com/',
              },
              location: {
                brewery_city: 'Petaluma',
                brewery_state: 'CA',
                lat: 38.2724,
                lng: -122.662,
              },
              brewery_active: 1,
            },
          },
          {
            checkin_count: 146281,
            have_had: false,
            your_count: 0,
            beer: {
              bid: 4170,
              beer_name: 'Scrimshaw',
              beer_label:
                'https://untappd.akamaized.net/site/beer_logos/beer-4170_2822d_sm.jpeg',
              beer_abv: 4.7,
              beer_slug: 'north-coast-brewing-company-scrimshaw',
              beer_ibu: 22,
              beer_description:
                'Named for the delicate engravings popularized by 19th century seafarers, Scrimshaw is a fresh tasting Pilsner brewed in the finest European tradition using Munich malt and, Hallertauer and Tettnang hops. Scrimshaw has a subtle hop character, a crisp, clean palate, and a dry finish.',
              created_at: 'Sat, 21 Aug 2010 14:26:35 +0000',
              beer_style: 'Pilsner - German',
              in_production: 1,
              auth_rating: 0,
              wish_list: false,
            },
            brewery: {
              brewery_id: 919,
              brewery_name: 'North Coast Brewing Company',
              brewery_slug: 'north-coast-brewing-company',
              brewery_page_url: '/w/north-coast-brewing-company/919',
              brewery_type: 'Regional Brewery',
              brewery_label:
                'https://untappd.akamaized.net/site/brewery_logos/brewery-NorthCoastBrewingCompany_919_d2110.jpeg',
              country_name: 'United States',
              contact: {
                twitter: 'NoCoastBrewCo',
                facebook: 'http://www.facebook.com/northcoastbrewingcompany',
                instagram: 'NorthCoastBrewingCompany',
                url: 'http://www.northcoastbrewing.com/',
              },
              location: {
                brewery_city: 'Fort Bragg',
                brewery_state: 'CA',
                lat: 39.4465,
                lng: -123.806,
              },
              brewery_active: 1,
            },
          },
          {
            checkin_count: 142126,
            have_had: false,
            your_count: 0,
            beer: {
              bid: 40173,
              beer_name: 'Veltins Pilsener',
              beer_label:
                'https://untappd.akamaized.net/site/beer_logos/beer-40173_77513_sm.jpeg',
              beer_abv: 4.8,
              beer_slug: 'brauerei-veltins-veltins-pilsener',
              beer_ibu: 30,
              beer_description: '',
              created_at: 'Sun, 27 Mar 2011 19:49:53 +0000',
              beer_style: 'Pilsner - German',
              in_production: 1,
              auth_rating: 0,
              wish_list: false,
            },
            brewery: {
              brewery_id: 207,
              brewery_name: 'Brauerei VELTINS',
              brewery_slug: 'brauerei-veltins',
              brewery_page_url: '/Brauerei_VELTINS',
              brewery_type: 'Micro Brewery',
              brewery_label:
                'https://untappd.akamaized.net/site/brewery_logos/brewery-207_604cd.jpeg',
              country_name: 'Germany',
              contact: {
                twitter: '',
                facebook: 'http://www.facebook.com/veltins',
                instagram: '',
                url: 'http://www.veltins.de',
              },
              location: {
                brewery_city: 'Meschede',
                brewery_state: 'Nordrhein-Westfalen',
                lat: 51.3065,
                lng: 8.12573,
              },
              brewery_active: 1,
            },
          },
          {
            checkin_count: 123894,
            have_had: false,
            your_count: 0,
            beer: {
              bid: 17259,
              beer_name: 'Efes Pilsen',
              beer_label:
                'https://untappd.akamaized.net/site/beer_logos/beer-17259_aa2d7_sm.jpeg',
              beer_abv: 5,
              beer_slug: 'anadolu-efes-efes-pilsen',
              beer_ibu: 22,
              beer_description: '',
              created_at: 'Sat, 25 Dec 2010 23:33:53 +0000',
              beer_style: 'Pilsner - Other',
              in_production: 1,
              auth_rating: 0,
              wish_list: false,
            },
            brewery: {
              brewery_id: 4568,
              brewery_name: 'Anadolu Efes',
              brewery_slug: 'anadolu-efes',
              brewery_page_url: '/EfesChamps',
              brewery_type: 'Macro Brewery',
              brewery_label:
                'https://untappd.akamaized.net/site/brewery_logos/brewery-4568_ca78c.jpeg',
              country_name: 'Turkey',
              contact: {
                twitter: '',
                facebook: '',
                instagram: '',
                url: 'http://www.anadoluefes.com.tr/',
              },
              location: {
                brewery_city: 'Istanbul',
                brewery_state: 'Istanbul',
                lat: 41.0182,
                lng: 29.1274,
              },
              brewery_active: 1,
            },
          },
          {
            checkin_count: 123521,
            have_had: false,
            your_count: 0,
            beer: {
              bid: 11517,
              beer_name: 'The Crisp',
              beer_label:
                'https://untappd.akamaized.net/site/beer_logos/beer-_11517_sm.jpeg',
              beer_abv: 5.4,
              beer_slug: 'sixpoint-brewery-the-crisp',
              beer_ibu: 44,
              beer_description:
                'The original Sehr Crisp from Sixpoint. Brewed with noble hops for indelible sehr crisp flavor.',
              created_at: 'Sat, 27 Nov 2010 18:58:25 +0000',
              beer_style: 'Pilsner - German',
              in_production: 1,
              auth_rating: 0,
              wish_list: false,
            },
            brewery: {
              brewery_id: 1149,
              brewery_name: 'Sixpoint Brewery',
              brewery_slug: 'sixpoint-brewery',
              brewery_page_url: '/sixpoint',
              brewery_type: 'Regional Brewery',
              brewery_label:
                'https://untappd.akamaized.net/site/brewery_logos/brewery-SixpointBrewery_1149.jpeg',
              country_name: 'United States',
              contact: {
                twitter: 'sixpoint',
                facebook: 'http://www.facebook.com/sixpoint',
                instagram: 'sixpoint',
                url: 'http://sixpoint.com/',
              },
              location: {
                brewery_city: 'Brooklyn',
                brewery_state: 'NY',
                lat: 40.674,
                lng: -74.0119,
              },
              brewery_active: 1,
            },
          },
          {
            checkin_count: 108754,
            have_had: false,
            your_count: 0,
            beer: {
              bid: 5325,
              beer_name: 'Jever Pilsener',
              beer_label:
                'https://untappd.akamaized.net/site/beer_logos/beer-5325_f4509_sm.jpeg',
              beer_abv: 4.9,
              beer_slug: 'friesisches-brauhaus-zu-jever-jever-pilsener',
              beer_ibu: 33,
              beer_description:
                'A Northern German (Friesian) Pilsener that is characteristic of the style. It is a little more hoppy than Czech pilseners giving it a more bitter ("herb" in German) flavour.',
              created_at: 'Sat, 21 Aug 2010 14:26:35 +0000',
              beer_style: 'Pilsner - German',
              in_production: 1,
              auth_rating: 0,
              wish_list: false,
            },
            brewery: {
              brewery_id: 124865,
              brewery_name: 'Friesisches Brauhaus zu Jever',
              brewery_slug: 'friesisches-brauhaus-zu-jever',
              brewery_page_url: '/w/friesisches-brauhaus-zu-jever/124865',
              brewery_type: 'Macro Brewery',
              brewery_label:
                'https://untappd.akamaized.net/site/brewery_logos/brewery-124865_55276.jpeg',
              country_name: 'Germany',
              contact: {
                twitter: '',
                facebook: 'http://www.facebook.com/jeverfriesischherb',
                instagram: '',
                url: 'http://www.jever.de',
              },
              location: {
                brewery_city: 'Jever',
                brewery_state: 'Niedersachsen',
                lat: 53.5755,
                lng: 7.90178,
              },
              brewery_active: 1,
            },
          },
          {
            checkin_count: 105739,
            have_had: false,
            your_count: 0,
            beer: {
              bid: 3841,
              beer_name: 'Sunshine Pils',
              beer_label:
                'https://untappd.akamaized.net/site/beer_logos/beer-3841_64639_sm.jpeg',
              beer_abv: 4.5,
              beer_slug: 'troegs-independent-brewing-sunshine-pils',
              beer_ibu: 45,
              beer_description:
                'It takes the right ingredients, people and processes to nail the complex balance of two-row barley, zesty Saaz hops and lager yeast. Secondary fermentation creates natural carbonation that delivers soft notes of fresh-cut straw and flowering herbs. In the end, this bright and refreshingly clean American craft pilsner is our go-to when the sun is shining and makes us happy when skies are gray. We taste: bright citrus, flowering herbs, honeyed biscuit',
              created_at: 'Sat, 21 Aug 2010 14:26:35 +0000',
              beer_style: 'Pilsner - German',
              in_production: 1,
              auth_rating: 0,
              wish_list: false,
            },
            brewery: {
              brewery_id: 2583,
              brewery_name: 'Tröegs Independent Brewing',
              brewery_slug: 'troegs-independent-brewing',
              brewery_page_url: '/troegsbrewingcompany',
              brewery_type: 'Regional Brewery',
              brewery_label:
                'https://untappd.akamaized.net/site/brewery_logos/brewery-2583_46be7.jpeg',
              country_name: 'United States',
              contact: {
                twitter: 'TroegsBeer',
                facebook: 'https://www.facebook.com/troegsbeer/',
                instagram: 'troegsbeer',
                url: 'http://www.troegs.com/',
              },
              location: {
                brewery_city: 'Hershey',
                brewery_state: 'PA',
                lat: 40.2933,
                lng: -76.6576,
              },
              brewery_active: 1,
            },
          },
          {
            checkin_count: 91985,
            have_had: false,
            your_count: 0,
            beer: {
              bid: 7521,
              beer_name: 'König Pilsener',
              beer_label:
                'https://untappd.akamaized.net/site/beer_logos/beer-7521_f882f_sm.jpeg',
              beer_abv: 4.9,
              beer_slug: 'konig-brauerei-konig-pilsener',
              beer_ibu: 32,
              beer_description:
                'An elegant effervescence gives way to malty sweetness intermingled with the delicate bitterness of herbs, finishing with a pleasant aftertaste. A well-balanced pilsner with an intense flavor but a delicately subtle overall impression.',
              created_at: 'Sat, 06 Nov 2010 11:40:08 +0000',
              beer_style: 'Pilsner - German',
              in_production: 1,
              auth_rating: 0,
              wish_list: false,
            },
            brewery: {
              brewery_id: 106179,
              brewery_name: 'König Brauerei',
              brewery_slug: 'konig-brauerei',
              brewery_page_url: '/Koenig-Brauerei',
              brewery_type: 'Macro Brewery',
              brewery_label:
                'https://untappd.akamaized.net/site/brewery_logos/brewery-106179_b0559.jpeg',
              country_name: 'Germany',
              contact: {
                twitter: '',
                facebook: 'http://www.facebook.com/KoenigPilsener',
                instagram: 'koenigpilsener',
                url: 'http://www.koenig.de',
              },
              location: {
                brewery_city: 'Duisburg',
                brewery_state: 'Nordrhein-Westfalen',
                lat: 51.5314,
                lng: 6.74178,
              },
              brewery_active: 1,
            },
          },
          {
            checkin_count: 87707,
            have_had: false,
            your_count: 0,
            beer: {
              bid: 7852,
              beer_name: 'Steam Whistle Pilsner',
              beer_label:
                'https://untappd.akamaized.net/site/beer_logos/beer-7852_8639d_sm.jpeg',
              beer_abv: 5,
              beer_slug: 'steam-whistle-brewing-steam-whistle-pilsner',
              beer_ibu: 22,
              beer_description:
                "'Do one thing really, really well' is Steam Whistle's motto and this Ontario fav is proof in the pudding. Pouring a medium gold with a fine head, the nose is fragrant with fresh hop aromas; the medium weight palate offers average carbonation with light grainy malt and floral character finishing with a refreshing bitterness.",
              created_at: 'Sun, 07 Nov 2010 16:40:15 +0000',
              beer_style: 'Pilsner - Other',
              in_production: 1,
              auth_rating: 0,
              wish_list: false,
            },
            brewery: {
              brewery_id: 1194,
              brewery_name: 'Steam Whistle Brewing',
              brewery_slug: 'steam-whistle-brewing',
              brewery_page_url: '/steamwhistlebrewing',
              brewery_type: 'Micro Brewery',
              brewery_label:
                'https://untappd.akamaized.net/site/brewery_logos/brewery-1194_820b4.jpeg',
              country_name: 'Canada',
              contact: {
                twitter: 'steamwhistle',
                facebook: 'http://www.facebook.com/SteamWhistle',
                instagram: '',
                url: 'http://www.steamwhistle.ca',
              },
              location: {
                brewery_city: 'Toronto',
                brewery_state: 'ON',
                lat: 43.6412,
                lng: -79.3852,
              },
              brewery_active: 1,
            },
          },
        ],
      },
      homebrew: { count: 0, items: [] },
      breweries: { items: [], count: 0 },
    },
  }
}
