import { rest } from 'msw'
import { url } from './venues-search'
import { FsVenuesSearchRes } from './venues-search.types'

export default rest.get(new RegExp('^' + url), (_, res, ctx) => {
  return res(ctx.status(200), ctx.json(getMockedData()))
})

function getMockedData(): FsVenuesSearchRes {
  return {
    meta: {
      code: 200,
      requestId: '',
    },
    notifications: [],
    response: {
      venues: [
        {
          id: '4b1809a0f964a520dccb23e3',
          name: 'Maltainen Riekko',
          location: {
            address: 'Aleksis Kiven katu 56',
            crossStreet: 'Kotkankatu',
            lat: 60.1924053811237,
            lng: 24.945079031059336,
            labeledLatLngs: [
              {
                label: 'display',
                lat: 60.1924053811237,
                lng: 24.945079031059336,
              },
            ],
            distance: 56,
            postalCode: '00510',
            cc: 'FI',
            city: 'Helsinki',
            state: 'Uusimaa',
            country: 'Suomi',
            formattedAddress: [
              'Aleksis Kiven katu 56 (Kotkankatu)',
              '00510 Helsinki',
              'Suomi',
            ],
          },
          categories: [
            {
              id: '4bf58dd8d48988d11b941735',
              name: 'Pub',
              pluralName: 'Pubs',
              shortName: 'Pub',
              icon: {
                prefix: 'https://ss3.4sqi.net/img/categories_v2/nightlife/pub_',
                suffix: '.png',
              },
              primary: true,
            },
          ],
          referralId: 'v-1595151424',
          hasPerk: false,
        },
        {
          id: '5cf5c8c96fd626002c4fbf65',
          name: 'Konepaja Biergarten',
          location: {
            address: 'Bruno Granholminkuja',
            crossStreet: 'Konepajanraitti',
            lat: 60.192886,
            lng: 24.947617,
            labeledLatLngs: [
              {
                label: 'display',
                lat: 60.192886,
                lng: 24.947617,
              },
            ],
            distance: 135,
            postalCode: '00510',
            cc: 'FI',
            neighborhood: 'Vallila',
            city: 'Helsinki',
            state: 'Uusimaa',
            country: 'Suomi',
            formattedAddress: [
              'Bruno Granholminkuja (Konepajanraitti)',
              '00510 Helsinki',
              'Suomi',
            ],
          },
          categories: [
            {
              id: '4bf58dd8d48988d117941735',
              name: 'Beer Garden',
              pluralName: 'Beer Gardens',
              shortName: 'Beer Garden',
              icon: {
                prefix: 'https://ss3.4sqi.net/img/categories_v2/nightlife/beergarden_',
                suffix: '.png',
              },
              primary: true,
            },
          ],
          referralId: 'v-1595151424',
          hasPerk: false,
        },
        {
          id: '58247f7aeaf46a6680eeada4',
          name: 'Korkkari 37',
          location: {
            lat: 60.191873,
            lng: 24.946151,
            labeledLatLngs: [
              {
                label: 'display',
                lat: 60.191873,
                lng: 24.946151,
              },
            ],
            distance: 27,
            cc: 'FI',
            country: 'Suomi',
            formattedAddress: ['Suomi'],
          },
          categories: [
            {
              id: '4bf58dd8d48988d107951735',
              name: 'Shoe Store',
              pluralName: 'Shoe Stores',
              shortName: 'Shoes',
              icon: {
                prefix: 'https://ss3.4sqi.net/img/categories_v2/shops/apparel_shoestore_',
                suffix: '.png',
              },
              primary: true,
            },
          ],
          referralId: 'v-1595151424',
          hasPerk: false,
        },
        {
          id: '532da2bc498e58f23b6c443b',
          name: 'Sauna',
          location: {
            lat: 60.19171,
            lng: 24.946133,
            labeledLatLngs: [
              {
                label: 'display',
                lat: 60.19171,
                lng: 24.946133,
              },
            ],
            distance: 42,
            cc: 'FI',
            country: 'Suomi',
            formattedAddress: ['Suomi'],
          },
          categories: [
            {
              id: '58daa1558bbb0b01f18ec1ae',
              name: 'Sauna / Steam Room',
              pluralName: 'Saunas / Steam Rooms',
              shortName: 'Sauna / Steam Room',
              icon: {
                prefix: 'https://ss3.4sqi.net/img/categories_v2/shops/spa_',
                suffix: '.png',
              },
              primary: true,
            },
          ],
          referralId: 'v-1595151424',
          hasPerk: false,
        },
        {
          id: '4cbc9ba54495721eb98f5b7a',
          name: 'HSL Raitiolinja 9',
          location: {
            address: 'Jätkäsaari - Rautatieasema - Kallio - Pasilan asema',
            lat: 60.16966350367054,
            lng: 24.93791341781616,
            labeledLatLngs: [
              {
                label: 'display',
                lat: 60.16966350367054,
                lng: 24.93791341781616,
              },
            ],
            distance: 2531,
            cc: 'FI',
            city: 'Helsinki',
            state: 'Uusimaa',
            country: 'Suomi',
            formattedAddress: [
              'Jätkäsaari - Rautatieasema - Kallio - Pasilan asema',
              'Helsinki',
              'Suomi',
            ],
          },
          categories: [
            {
              id: '52f2ab2ebcbc57f1066b8b50',
              name: 'Cable Car',
              pluralName: 'Cable Cars',
              shortName: 'Cable Car',
              icon: {
                prefix: 'https://ss3.4sqi.net/img/categories_v2/travel/trainstation_',
                suffix: '.png',
              },
              primary: true,
            },
          ],
          referralId: 'v-1595151424',
          hasPerk: false,
        },
        {
          id: '5aec16484940bc00396dc7b0',
          name: 'R-kioski',
          location: {
            address: 'Konepajankuja 1',
            crossStreet: 'Aleksis Kiven katu',
            lat: 60.191142761034,
            lng: 24.948749542236328,
            labeledLatLngs: [
              {
                label: 'display',
                lat: 60.191142761034,
                lng: 24.948749542236328,
              },
            ],
            distance: 191,
            postalCode: '00510',
            cc: 'FI',
            city: 'Helsinki',
            state: 'Uusimaa',
            country: 'Suomi',
            formattedAddress: [
              'Konepajankuja 1 (Aleksis Kiven katu)',
              '00510 Helsinki',
              'Suomi',
            ],
          },
          categories: [
            {
              id: '4d954b0ea243a5684a65b473',
              name: 'Convenience Store',
              pluralName: 'Convenience Stores',
              shortName: 'Convenience Store',
              icon: {
                prefix: 'https://ss3.4sqi.net/img/categories_v2/shops/conveniencestore_',
                suffix: '.png',
              },
              primary: true,
            },
          ],
          referralId: 'v-1595151424',
          hasPerk: false,
        },
        {
          id: '4e22f3fd6365caf119587f2e',
          name: 'Kohu-Live Oy',
          location: {
            address: 'Aleksis Kiven katu 52-54 A',
            crossStreet: 'Kajaaninkatu',
            lat: 60.19182809466445,
            lng: 24.94594931602478,
            labeledLatLngs: [
              {
                label: 'display',
                lat: 60.19182809466445,
                lng: 24.94594931602478,
              },
            ],
            distance: 26,
            postalCode: '00510',
            cc: 'FI',
            city: 'Helsinki',
            state: 'Uusimaa',
            country: 'Suomi',
            formattedAddress: [
              'Aleksis Kiven katu 52-54 A (Kajaaninkatu)',
              '00510 Helsinki',
              'Suomi',
            ],
          },
          categories: [
            {
              id: '4bf58dd8d48988d124941735',
              name: 'Office',
              pluralName: 'Offices',
              shortName: 'Office',
              icon: {
                prefix: 'https://ss3.4sqi.net/img/categories_v2/building/default_',
                suffix: '.png',
              },
              primary: true,
            },
          ],
          referralId: 'v-1595151424',
          hasPerk: false,
        },
        {
          id: '4d8334565e70224b5342f208',
          name: 'Cosa Nostra Crew Oy',
          location: {
            address: 'Aleksis Kiven katu 17 A',
            lat: 60.19231608615422,
            lng: 24.946067333221436,
            labeledLatLngs: [
              {
                label: 'display',
                lat: 60.19231608615422,
                lng: 24.946067333221436,
              },
            ],
            distance: 31,
            postalCode: '00510',
            cc: 'FI',
            city: 'Helsinki',
            state: 'Uusimaa',
            country: 'Suomi',
            formattedAddress: ['Aleksis Kiven katu 17 A', '00510 Helsinki', 'Suomi'],
          },
          categories: [
            {
              id: '4bf58dd8d48988d1f8941735',
              name: 'Furniture / Home Store',
              pluralName: 'Furniture / Home Stores',
              shortName: 'Furniture / Home',
              icon: {
                prefix: 'https://ss3.4sqi.net/img/categories_v2/shops/furniture_',
                suffix: '.png',
              },
              primary: true,
            },
          ],
          referralId: 'v-1595151424',
          hasPerk: false,
        },
        {
          id: '5df20c9b8a06ab000897489f',
          name: 'Yarsa',
          location: {
            address: 'Kajaaninkatu 2',
            lat: 60.191364096027634,
            lng: 24.945101737976074,
            labeledLatLngs: [
              {
                label: 'display',
                lat: 60.191364096027634,
                lng: 24.945101737976074,
              },
            ],
            distance: 87,
            postalCode: '00510',
            cc: 'FI',
            city: 'Helsinki',
            state: 'Uusimaa',
            country: 'Suomi',
            formattedAddress: ['Kajaaninkatu 2', '00510 Helsinki', 'Suomi'],
          },
          categories: [
            {
              id: '52e81612bcbc57f1066b79fb',
              name: 'Himalayan Restaurant',
              pluralName: 'Himalayan Restaurants',
              shortName: 'Himalayan',
              icon: {
                prefix: 'https://ss3.4sqi.net/img/categories_v2/food/default_',
                suffix: '.png',
              },
              primary: true,
            },
          ],
          referralId: 'v-1595151424',
          hasPerk: false,
        },
        {
          id: '4bf8077d5317a593d4fffe7e',
          name: 'Dallapénpuisto',
          location: {
            address: 'Aleksis Kiven katu',
            crossStreet: 'Kustaankatu',
            lat: 60.18973085051361,
            lng: 24.95817454711987,
            labeledLatLngs: [
              {
                label: 'display',
                lat: 60.18973085051361,
                lng: 24.95817454711987,
              },
            ],
            distance: 730,
            postalCode: '00510',
            cc: 'FI',
            city: 'Helsinki',
            state: 'Uusimaa',
            country: 'Suomi',
            formattedAddress: [
              'Aleksis Kiven katu (Kustaankatu)',
              '00510 Helsinki',
              'Suomi',
            ],
          },
          categories: [
            {
              id: '4bf58dd8d48988d163941735',
              name: 'Park',
              pluralName: 'Parks',
              shortName: 'Park',
              icon: {
                prefix: 'https://ss3.4sqi.net/img/categories_v2/parks_outdoors/park_',
                suffix: '.png',
              },
              primary: true,
            },
          ],
          referralId: 'v-1595151424',
          hasPerk: false,
        },
        {
          id: '4bcb1a17fb84c9b6e21e1e3e',
          name: 'K-Market',
          location: {
            address: 'Porvoonkatu 19',
            lat: 60.190822673994305,
            lng: 24.94578246576255,
            labeledLatLngs: [
              {
                label: 'display',
                lat: 60.190822673994305,
                lng: 24.94578246576255,
              },
            ],
            distance: 137,
            postalCode: '00510',
            cc: 'FI',
            city: 'Helsinki',
            state: 'Uusimaa',
            country: 'Suomi',
            formattedAddress: ['Porvoonkatu 19', '00510 Helsinki', 'Suomi'],
          },
          categories: [
            {
              id: '4bf58dd8d48988d118951735',
              name: 'Grocery Store',
              pluralName: 'Grocery Stores',
              shortName: 'Grocery Store',
              icon: {
                prefix: 'https://ss3.4sqi.net/img/categories_v2/shops/food_grocery_',
                suffix: '.png',
              },
              primary: true,
            },
          ],
          referralId: 'v-1595151424',
          hasPerk: false,
        },
        {
          id: '4adcdb1ff964a5209b5f21e3',
          name: 'Weeruska',
          location: {
            address: 'Porvoonkatu 19',
            lat: 60.19089974943469,
            lng: 24.94648758400165,
            labeledLatLngs: [
              {
                label: 'display',
                lat: 60.19089974943469,
                lng: 24.94648758400165,
              },
            ],
            distance: 134,
            postalCode: '00510',
            cc: 'FI',
            city: 'Helsinki',
            state: 'Uusimaa',
            country: 'Suomi',
            formattedAddress: ['Porvoonkatu 19', '00510 Helsinki', 'Suomi'],
          },
          categories: [
            {
              id: '4bf58dd8d48988d155941735',
              name: 'Gastropub',
              pluralName: 'Gastropubs',
              shortName: 'Gastropub',
              icon: {
                prefix: 'https://ss3.4sqi.net/img/categories_v2/food/gastropub_',
                suffix: '.png',
              },
              primary: true,
            },
          ],
          referralId: 'v-1595151424',
          hasPerk: false,
        },
        {
          id: '591dfcd2c5b11c20a309d241',
          name: 'Aleksis Kiven katu 56',
          location: {
            address: 'Aleksis Kiven katu 56',
            lat: 60.19228697484155,
            lng: 24.945008260298856,
            labeledLatLngs: [
              {
                label: 'display',
                lat: 60.19228697484155,
                lng: 24.945008260298856,
              },
            ],
            distance: 52,
            postalCode: '00510',
            cc: 'FI',
            city: 'Helsinki',
            state: 'Uusimaa',
            country: 'Suomi',
            formattedAddress: ['Aleksis Kiven katu 56', '00510 Helsinki', 'Suomi'],
          },
          categories: [
            {
              id: '4d954b06a243a5684965b473',
              name: 'Residential Building (Apartment / Condo)',
              pluralName: 'Residential Buildings (Apartments / Condos)',
              shortName: 'Residential',
              icon: {
                prefix: 'https://ss3.4sqi.net/img/categories_v2/building/apartment_',
                suffix: '.png',
              },
              primary: true,
            },
          ],
          referralId: 'v-1595151424',
          hasPerk: false,
        },
        {
          id: '5329f752498eb82f143e158c',
          name: 'Golden Rice Bowl',
          location: {
            address: 'Porvoonkatu 16',
            lat: 60.190838,
            lng: 24.944493,
            labeledLatLngs: [
              {
                label: 'display',
                lat: 60.190838,
                lng: 24.944493,
              },
            ],
            distance: 154,
            postalCode: '00510',
            cc: 'FI',
            city: 'Helsinki',
            state: 'Uusimaa',
            country: 'Suomi',
            formattedAddress: ['Porvoonkatu 16', '00510 Helsinki', 'Suomi'],
          },
          categories: [
            {
              id: '4bf58dd8d48988d145941735',
              name: 'Chinese Restaurant',
              pluralName: 'Chinese Restaurants',
              shortName: 'Chinese',
              icon: {
                prefix: 'https://ss3.4sqi.net/img/categories_v2/food/asian_',
                suffix: '.png',
              },
              primary: true,
            },
          ],
          referralId: 'v-1595151424',
          hasPerk: false,
        },
        {
          id: '4e96e79c0aafdb60e0a603b6',
          name: 'Alppila GYM 24',
          location: {
            address: 'Viipurinkatu 7',
            lat: 60.191236550155516,
            lng: 24.94398426491986,
            labeledLatLngs: [
              {
                label: 'display',
                lat: 60.191236550155516,
                lng: 24.94398426491986,
              },
            ],
            distance: 137,
            postalCode: '00510',
            cc: 'FI',
            city: 'Helsinki',
            country: 'Suomi',
            formattedAddress: ['Viipurinkatu 7', '00510 Helsinki', 'Suomi'],
          },
          categories: [
            {
              id: '4bf58dd8d48988d176941735',
              name: 'Gym',
              pluralName: 'Gyms',
              shortName: 'Gym',
              icon: {
                prefix: 'https://ss3.4sqi.net/img/categories_v2/building/gym_',
                suffix: '.png',
              },
              primary: true,
            },
          ],
          referralId: 'v-1595151424',
          hasPerk: false,
        },
        {
          id: '4cdeb0b269136dcb57d6d7e6',
          name: 'Kuuskulma',
          location: {
            address: 'Porvoonkatu',
            crossStreet: 'a.k.a Porvoonkadun aukio',
            lat: 60.191456917195275,
            lng: 24.943318051795796,
            labeledLatLngs: [
              {
                label: 'display',
                lat: 60.191456917195275,
                lng: 24.943318051795796,
              },
            ],
            distance: 154,
            cc: 'FI',
            city: 'Helsinki',
            state: 'Uusimaa',
            country: 'Suomi',
            formattedAddress: [
              'Porvoonkatu (a.k.a Porvoonkadun aukio)',
              'Helsinki',
              'Suomi',
            ],
          },
          categories: [
            {
              id: '4bf58dd8d48988d164941735',
              name: 'Plaza',
              pluralName: 'Plazas',
              shortName: 'Plaza',
              icon: {
                prefix: 'https://ss3.4sqi.net/img/categories_v2/parks_outdoors/plaza_',
                suffix: '.png',
              },
              primary: true,
            },
          ],
          referralId: 'v-1595151424',
          hasPerk: false,
        },
        {
          id: '55f32b4d498ed2c829de7b7d',
          name: 'Alppilan Huone',
          location: {
            address: 'Porvoonkatu 19',
            lat: 60.190893483849216,
            lng: 24.945555673828174,
            labeledLatLngs: [
              {
                label: 'display',
                lat: 60.190893483849216,
                lng: 24.945555673828174,
              },
            ],
            distance: 130,
            postalCode: '00510',
            cc: 'FI',
            city: 'Helsinki',
            state: 'Uusimaa',
            country: 'Suomi',
            formattedAddress: ['Porvoonkatu 19', '00510 Helsinki', 'Suomi'],
          },
          categories: [
            {
              id: '4bf58dd8d48988d116941735',
              name: 'Bar',
              pluralName: 'Bars',
              shortName: 'Bar',
              icon: {
                prefix: 'https://ss3.4sqi.net/img/categories_v2/nightlife/pub_',
                suffix: '.png',
              },
              primary: true,
            },
          ],
          referralId: 'v-1595151424',
          hasPerk: false,
        },
        {
          id: '5ac738a19411f2617679bc34',
          name: 'saigon beauty',
          location: {
            address: 'Aleksis Kven Katu 19',
            lat: 60.191516,
            lng: 24.947391,
            labeledLatLngs: [
              {
                label: 'display',
                lat: 60.191516,
                lng: 24.947391,
              },
            ],
            distance: 105,
            postalCode: '00510',
            cc: 'FI',
            city: 'Helsinki',
            state: 'Uusimaa',
            country: 'Suomi',
            formattedAddress: ['Aleksis Kven Katu 19', '00510 Helsinki', 'Suomi'],
          },
          categories: [
            {
              id: '4f04aa0c2fb6e1c99f3db0b8',
              name: 'Nail Salon',
              pluralName: 'Nail Salons',
              shortName: 'Nail Salon',
              icon: {
                prefix: 'https://ss3.4sqi.net/img/categories_v2/shops/nailsalon_',
                suffix: '.png',
              },
              primary: true,
            },
          ],
          referralId: 'v-1595151424',
          hasPerk: false,
        },
        {
          id: '50e46bf8e4b0f6dd2c6a7756',
          name: 'soikun&metukan loft',
          location: {
            lat: 60.191967499622244,
            lng: 24.94577544757206,
            labeledLatLngs: [
              {
                label: 'display',
                lat: 60.191967499622244,
                lng: 24.94577544757206,
              },
            ],
            distance: 10,
            cc: 'FI',
            country: 'Suomi',
            formattedAddress: ['Suomi'],
          },
          categories: [
            {
              id: '4d954b06a243a5684965b473',
              name: 'Residential Building (Apartment / Condo)',
              pluralName: 'Residential Buildings (Apartments / Condos)',
              shortName: 'Residential',
              icon: {
                prefix: 'https://ss3.4sqi.net/img/categories_v2/building/apartment_',
                suffix: '.png',
              },
              primary: true,
            },
          ],
          referralId: 'v-1595151424',
          hasPerk: false,
        },
        {
          id: '58478c3704aa4f38cdcfe9bc',
          name: 'K-market Alppila',
          location: {
            lat: 60.190884,
            lng: 24.94618,
            labeledLatLngs: [
              {
                label: 'display',
                lat: 60.190884,
                lng: 24.94618,
              },
            ],
            distance: 132,
            cc: 'FI',
            country: 'Suomi',
            formattedAddress: ['Suomi'],
          },
          categories: [
            {
              id: '4bf58dd8d48988d118951735',
              name: 'Grocery Store',
              pluralName: 'Grocery Stores',
              shortName: 'Grocery Store',
              icon: {
                prefix: 'https://ss3.4sqi.net/img/categories_v2/shops/food_grocery_',
                suffix: '.png',
              },
              primary: true,
            },
          ],
          referralId: 'v-1595151424',
          hasPerk: false,
        },
        {
          id: '4f831db8c2ee0bc7deeb83c1',
          name: 'Aleksis Kiven katu 52',
          location: {
            address: 'Aleksis Kiven katu 52',
            crossStreet: 'kajaaninkatu',
            lat: 60.19182542802435,
            lng: 24.945895671844482,
            labeledLatLngs: [
              {
                label: 'display',
                lat: 60.19182542802435,
                lng: 24.945895671844482,
              },
            ],
            distance: 26,
            postalCode: '00510',
            cc: 'FI',
            city: 'Helsinki',
            state: 'Uusimaa',
            country: 'Suomi',
            formattedAddress: [
              'Aleksis Kiven katu 52 (kajaaninkatu)',
              '00510 Helsinki',
              'Suomi',
            ],
          },
          categories: [
            {
              id: '4d954b06a243a5684965b473',
              name: 'Residential Building (Apartment / Condo)',
              pluralName: 'Residential Buildings (Apartments / Condos)',
              shortName: 'Residential',
              icon: {
                prefix: 'https://ss3.4sqi.net/img/categories_v2/building/apartment_',
                suffix: '.png',
              },
              primary: true,
            },
          ],
          referralId: 'v-1595151424',
          hasPerk: false,
        },
        {
          id: '4e6730567d8b084ac737c175',
          name: 'HSL 0631 Porvoonkatu',
          location: {
            address: 'Porvoonkatu',
            lat: 60.19079104275778,
            lng: 24.945331660885923,
            labeledLatLngs: [
              {
                label: 'display',
                lat: 60.19079104275778,
                lng: 24.945331660885923,
              },
            ],
            distance: 143,
            cc: 'FI',
            city: 'Helsinki',
            state: 'Uusimaa',
            country: 'Suomi',
            formattedAddress: ['Porvoonkatu', 'Helsinki', 'Suomi'],
          },
          categories: [
            {
              id: '52f2ab2ebcbc57f1066b8b51',
              name: 'Tram Station',
              pluralName: 'Tram Stations',
              shortName: 'Tram',
              icon: {
                prefix: 'https://ss3.4sqi.net/img/categories_v2/travel/trainstation_',
                suffix: '.png',
              },
              primary: true,
            },
          ],
          referralId: 'v-1595151424',
          hasPerk: false,
        },
        {
          id: '4e9d48dd49017c00c872e342',
          name: 'HSL 2134 Kotkankatu',
          location: {
            address: 'Aleksis Kiven katu',
            lat: 60.19258973419905,
            lng: 24.944502007592767,
            labeledLatLngs: [
              {
                label: 'display',
                lat: 60.19258973419905,
                lng: 24.944502007592767,
              },
            ],
            distance: 94,
            postalCode: '00510',
            cc: 'FI',
            city: 'Helsinki',
            state: 'Uusimaa',
            country: 'Suomi',
            formattedAddress: ['Aleksis Kiven katu', '00510 Helsinki', 'Suomi'],
          },
          categories: [
            {
              id: '52f2ab2ebcbc57f1066b8b4f',
              name: 'Bus Stop',
              pluralName: 'Bus Stops',
              shortName: 'Bus Stop',
              icon: {
                prefix: 'https://ss3.4sqi.net/img/categories_v2/travel/busstation_',
                suffix: '.png',
              },
              primary: true,
            },
          ],
          referralId: 'v-1595151424',
          hasPerk: false,
        },
        {
          id: '573c65e6cd10a6a66e6a031b',
          name: 'Konepajanportti',
          location: {
            lat: 60.192394,
            lng: 24.945772,
            labeledLatLngs: [
              {
                label: 'display',
                lat: 60.192394,
                lng: 24.945772,
              },
            ],
            distance: 37,
            cc: 'FI',
            country: 'Suomi',
            formattedAddress: ['Suomi'],
          },
          categories: [
            {
              id: '56aa371be4b08b9a8d573517',
              name: 'Business Center',
              pluralName: 'Business Centers',
              shortName: 'Business Center',
              icon: {
                prefix: 'https://ss3.4sqi.net/img/categories_v2/building/default_',
                suffix: '.png',
              },
              primary: true,
            },
          ],
          referralId: 'v-1595151424',
          hasPerk: false,
        },
        {
          id: '5e6baf008fb2680008e4c0c1',
          name: 'Chill & Grill',
          location: {
            address: 'Porvoonkatu 23',
            lat: 60.191315,
            lng: 24.94479,
            labeledLatLngs: [
              {
                label: 'display',
                lat: 60.191315,
                lng: 24.94479,
              },
            ],
            distance: 100,
            postalCode: '00510',
            cc: 'FI',
            city: 'Helsinki',
            state: 'Uusimaa',
            country: 'Suomi',
            formattedAddress: ['Porvoonkatu 23', '00510 Helsinki', 'Suomi'],
          },
          categories: [
            {
              id: '4bf58dd8d48988d11d941735',
              name: 'Sports Bar',
              pluralName: 'Sports Bars',
              shortName: 'Sports Bar',
              icon: {
                prefix: 'https://ss3.4sqi.net/img/categories_v2/nightlife/sportsbar_',
                suffix: '.png',
              },
              primary: true,
            },
          ],
          referralId: 'v-1595151424',
          hasPerk: false,
        },
        {
          id: '5bfe7dec835c9a002cff8556',
          name: 'The Train Factory',
          location: {
            address: 'Konepajanportti',
            lat: 60.192376,
            lng: 24.946318,
            labeledLatLngs: [
              {
                label: 'display',
                lat: 60.192376,
                lng: 24.946318,
              },
            ],
            distance: 44,
            postalCode: '00510',
            cc: 'FI',
            city: 'Helsinki',
            state: 'Uusimaa',
            country: 'Suomi',
            formattedAddress: ['Konepajanportti', '00510 Helsinki', 'Suomi'],
          },
          categories: [
            {
              id: '4bf58dd8d48988d171941735',
              name: 'Event Space',
              pluralName: 'Event Spaces',
              shortName: 'Event Space',
              icon: {
                prefix: 'https://ss3.4sqi.net/img/categories_v2/building/eventspace_',
                suffix: '.png',
              },
              primary: true,
            },
          ],
          referralId: 'v-1595151424',
          hasPerk: false,
        },
        {
          id: '4cce94f8aa25a35dcc4c210f',
          name: 'A-katsastus',
          location: {
            address: 'Aleksis Kiven katu 17',
            crossStreet: 'Aleksis Kiven Kadun Katsastusasema',
            lat: 60.19267403356582,
            lng: 24.947993937247116,
            labeledLatLngs: [
              {
                label: 'display',
                lat: 60.19267403356582,
                lng: 24.947993937247116,
              },
            ],
            distance: 137,
            postalCode: '00510',
            cc: 'FI',
            city: 'Helsinki',
            state: 'Southern Finland',
            country: 'Suomi',
            formattedAddress: [
              'Aleksis Kiven katu 17 (Aleksis Kiven Kadun Katsastusasema)',
              '00510 Helsinki',
              'Suomi',
            ],
          },
          categories: [
            {
              id: '4bf58dd8d48988d124951735',
              name: 'Automotive Shop',
              pluralName: 'Automotive Shops',
              shortName: 'Automotive',
              icon: {
                prefix: 'https://ss3.4sqi.net/img/categories_v2/shops/automotive_',
                suffix: '.png',
              },
              primary: true,
            },
          ],
          referralId: 'v-1595151424',
          hasPerk: false,
        },
        {
          id: '5dbd5ea036f7bd0008c06fb1',
          name: 'Studio Kupu',
          location: {
            address: 'Viipurinkatu 8',
            lat: 60.190947,
            lng: 24.944237,
            labeledLatLngs: [
              {
                label: 'display',
                lat: 60.190947,
                lng: 24.944237,
              },
            ],
            distance: 151,
            postalCode: '00510',
            cc: 'FI',
            city: 'Helsinki',
            state: 'Uusimaa',
            country: 'Suomi',
            formattedAddress: ['Viipurinkatu 8', '00510 Helsinki', 'Suomi'],
          },
          categories: [
            {
              id: '554a5e17498efabeda6cc559',
              name: 'Photography Studio',
              pluralName: 'Photography Studios',
              shortName: 'Photo Studio',
              icon: {
                prefix: 'https://ss3.4sqi.net/img/categories_v2/shops/camerastore_',
                suffix: '.png',
              },
              primary: true,
            },
          ],
          referralId: 'v-1595151424',
          hasPerk: false,
        },
        {
          id: '4e5f740888771c94689e513a',
          name: 'HSL 0632 Porvoonkatu',
          location: {
            address: 'Porvoonkatu 12',
            lat: 60.19082544118363,
            lng: 24.945581581485776,
            labeledLatLngs: [
              {
                label: 'display',
                lat: 60.19082544118363,
                lng: 24.945581581485776,
              },
            ],
            distance: 138,
            postalCode: '00510',
            cc: 'FI',
            city: 'Helsinki',
            state: 'Uusimaa',
            country: 'Suomi',
            formattedAddress: ['Porvoonkatu 12', '00510 Helsinki', 'Suomi'],
          },
          categories: [
            {
              id: '52f2ab2ebcbc57f1066b8b51',
              name: 'Tram Station',
              pluralName: 'Tram Stations',
              shortName: 'Tram',
              icon: {
                prefix: 'https://ss3.4sqi.net/img/categories_v2/travel/trainstation_',
                suffix: '.png',
              },
              primary: true,
            },
          ],
          referralId: 'v-1595151424',
          hasPerk: false,
        },
        {
          id: '5cf0f127829b0c002c07a26b',
          name: 'HUG Café',
          location: {
            address: 'Porvoonkatu 14',
            lat: 60.190687,
            lng: 24.945097,
            labeledLatLngs: [
              {
                label: 'display',
                lat: 60.190687,
                lng: 24.945097,
              },
            ],
            distance: 158,
            postalCode: '00510',
            cc: 'FI',
            city: 'Helsinki',
            state: 'Uusimaa',
            country: 'Suomi',
            formattedAddress: ['Porvoonkatu 14', '00510 Helsinki', 'Suomi'],
          },
          categories: [
            {
              id: '4bf58dd8d48988d16d941735',
              name: 'Café',
              pluralName: 'Cafés',
              shortName: 'Café',
              icon: {
                prefix: 'https://ss3.4sqi.net/img/categories_v2/food/cafe_',
                suffix: '.png',
              },
              primary: true,
            },
          ],
          referralId: 'v-1595151424',
          hasPerk: false,
        },
      ],
    },
  }
}
